defaults:
    - _self_
    - sac
    
# this needs to be specified manually
experiment: PEBBLE

# reward learning
segment: 50
activation: leaky_relu
num_seed_steps: 1000 #1000
num_unsup_steps: 5000 #5000
num_interact: 5000
reward_lr: 0.0003
reward_batch: 128
reward_update: 200
feed_type: 0
reset_update: 100
topK: 5
ensemble_size: 3
max_feedback: 1400
large_batch: 10
label_margin: 0.0
reward_scale: 1.0
reward_intercept: 0.0
human_teacher: False
teacher_beta: -1    # Rationality Constant 0 leads to random choices and infinite (-1) to perfectly rational
teacher_gamma: 1    # Discound Factor for myopic behavior paying more attention on recent states
teacher_eps_mistake: 0  # Probability of mistake
teacher_eps_skip: 0     # Probability of considering both segments bad
teacher_eps_equal: 0    # Probability of considering both segments equally good

# scheduling
reward_schedule: 0

num_train_steps: 1000000
replay_buffer_capacity: ${num_train_steps}

# evaluation config
eval_frequency: 50 #10000
num_eval_episodes: 10
device: cpu

# logger
log_frequency: 10000
log_save_tb: true

# video recorder
save_video: false

# setups
seed: 1
debug: False

# Environment
domain: Control
env: Ant-v4
render_mode: None
#max_episode_steps: 100
gradient_update: 1

#Atari Settings
obs_type: rgb # [states, pixels]
frame_stack: 4 # only works if obs_type=pixels
frameskip: 4
action_repeat: 1 # set to 2 for pixels
mode :
difficulty :
repeat_action_probability: 0.25
full_action_space:

# Snapshot
snapshots: [100000, 500000, 1000000, 2000000]
snapshot_dir: models/${obs_type}/${env}/sac/
